cleanJar {
	doLast {
		project.delete(rootProject.file("../${project.name}/${project.name}.jar"))
	}
}

dependencies {
	compileOnly "javax.enterprise.deploy:deployment-api:1.2-rev-1"
	compileOnly "com.liferay:org.freemarker:2.3.29.LIFERAY-PATCHED-2"
	compileOnly "jalopy:jalopy:1.5rc3"
	compileOnly "org.osgi:org.osgi.annotation.versioning:1.1.0"
	compileOnly "org.postgresql:postgresql:42.2.5"
	compileOnly "com.thoughtworks.qdox:qdox:1.12.1"
	compileOnly "javax.servlet:javax.servlet-api:3.1.0"
	compileOnly "org.springframework:spring-test:5.2.10.RELEASE"
	compileOnly "org.apache.velocity:velocity:1.6.4"

	compileOnly group: "antlr", name: "antlr", version: "2.7.7"
	compileOnly group: "bsf", name: "bsf", version: "2.4.0"
	compileOnly group: "cglib", name: "cglib-nodep", version: "2.2.2"
	compileOnly group: "com.adobe.xmp", name: "xmpcore", version: "6.0.6"
	compileOnly group: "com.drewnoakes", name: "metadata-extractor", version: "2.13.0"
	compileOnly group: "com.github.jai-imageio", name: "jai-imageio-core", version: "1.4.0"
	compileOnly group: "com.github.jai-imageio", name: "jai-imageio-jpeg2000", version: "1.3.0"
	compileOnly group: "com.github.virtuald", name: "curvesapi", version: "1.06"
	compileOnly group: "com.google.javascript", name: "closure-compiler", version: "v20131014"
	compileOnly group: "com.googlecode.juniversalchardet", name: "juniversalchardet", version: "1.0.3"
	compileOnly group: "com.liferay", name: "asm", version: "7.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "asm.analysis", version: "7.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "asm.commons", version: "7.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "asm.tree", version: "7.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "asm.util", version: "7.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "com.artofsolving.jodconverter", version: "2.2.2"
	compileOnly group: "com.liferay", name: "com.coucho.hessian", version: "4.0.3"
	compileOnly group: "com.liferay", name: "com.fasterxml.jackson.databind", version: "2.10.3.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "com.hp.hpl.jena", version: "1.4"
	compileOnly group: "com.liferay", name: "com.ibm.icu4j", version: "54.1.1.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay", name: "com.megginson.sax.rdf", version: "1.0"
	compileOnly group: "com.liferay", name: "com.sun.syndication", version: "1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "com.sun.xml.ws", version: "2.1.7.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "de.l3s.boilerpipe", version: "1.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "javax.ccpp.ccpp-ri", version: "1.0"
	compileOnly group: "com.liferay", name: "javax.jws", version: "1.1.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "javax.xml.bind", version: "2.3.0.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay", name: "javax.xml.rpc", version: "1.1"
	compileOnly group: "com.liferay", name: "javax.xml.soap", version: "1.4.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "javax.xml.ws", version: "2.3.0.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "jodd.util", version: "6.0.1.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "net.jmge.gif.gif89", version: "1.0"
	compileOnly group: "com.liferay", name: "org.apache.axis", version: "1.4.LIFERAY-PATCHED-6"
	compileOnly group: "com.liferay", name: "org.apache.commons.configuration", version: "1.10.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay", name: "org.apache.commons.jrcs.diff", version: "0.3.0"
	compileOnly group: "com.liferay", name: "org.apache.logging.log4j", version: "2.14.1.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.apache.logging.log4j.core", version: "2.14.1.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.apache.regexp", version: "1.5"
	compileOnly group: "com.liferay", name: "org.bouncycastle.mail", version: "1.61.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.bouncycastle.provider", version: "1.61.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.gagravarr.tika", version: "0.8.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.hibernate.core", version: "3.6.10.LIFERAY-PATCHED-6"
	compileOnly group: "com.liferay", name: "org.jabsorb", version: "1.3.2.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.monte", version: "0.7.7"
	compileOnly group: "com.liferay", name: "org.mozilla.intl.chardet", version: "1.1"
	compileOnly group: "com.liferay", name: "org.mp4parser", version: "1.9.41.2.LIFERAY-PATCHED-2"
	compileOnly group: "com.liferay", name: "org.outerj.daisy.diff", version: "1.2.0-atlassian-hosted.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.springframework.orm", version: "4.3.22.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.vps.crypt", version: "1.0"
	compileOnly group: "com.liferay", name: "xuggle.xuggler.noarch", version: "5.4"
	compileOnly group: "com.liferay.portletmvc4spring", name: "com.liferay.portletmvc4spring.framework", version: "5.2.0"
	compileOnly group: "com.mchange", name: "c3p0", version: "0.9.5.4"
	compileOnly group: "com.mchange", name: "mchange-commons-java", version: "0.2.15"
	compileOnly group: "com.pff", name: "java-libpst", version: "0.8.1"
	compileOnly group: "com.rometools", name: "rome", version: "1.12.2"
	compileOnly group: "com.rometools", name: "rome-utils", version: "1.12.2"
	compileOnly group: "com.sun", name: "jai_core", version: "1.1.3"
	compileOnly group: "com.sun.media", name: "jai-codec", version: "1.1.3"
	compileOnly group: "com.sun.xml.bind", name: "jaxb-impl", version: "2.1.17"
	compileOnly group: "com.sun.xml.messaging.saaj", name: "saaj-impl", version: "1.3"
	compileOnly group: "com.sun.xml.stream.buffer", name: "streambuffer", version: "0.9"
	compileOnly group: "com.thoughtworks.xstream", name: "xstream", version: "1.4.16"
	compileOnly group: "com.uwyn", name: "jhighlight", version: "1.0"
	compileOnly group: "com.yahoo.platform.yui", name: "yuicompressor", version: "2.4.8"
	compileOnly group: "com.zaxxer", name: "HikariCP", version: "2.6.3"
	compileOnly group: "com.zaxxer", name: "SparseBitSet", version: "1.2"
	compileOnly group: "commons-beanutils", name: "commons-beanutils", version: "1.9.4"
	compileOnly group: "commons-chain", name: "commons-chain", version: "1.2"
	compileOnly group: "commons-codec", name: "commons-codec", version: "1.13"
	compileOnly group: "commons-collections", name: "commons-collections", version: "3.2.2"
	compileOnly group: "commons-dbcp", name: "commons-dbcp", version: "1.2.2"
	compileOnly group: "commons-digester", name: "commons-digester", version: "1.8.1"
	compileOnly group: "commons-discovery", name: "commons-discovery", version: "0.4"
	compileOnly group: "commons-fileupload", name: "commons-fileupload", version: "1.3.3"
	compileOnly group: "commons-io", name: "commons-io", version: "2.5"
	compileOnly group: "commons-lang", name: "commons-lang", version: "2.6"
	compileOnly group: "commons-logging", name: "commons-logging", version: "1.2"
	compileOnly group: "commons-pool", name: "commons-pool", version: "1.5.7"
	compileOnly group: "commons-validator", name: "commons-validator", version: "1.5.1"
	compileOnly group: "concurrent", name: "concurrent", version: "1.3.4"
	compileOnly group: "displaytag", name: "displaytag", version: "1.2"
	compileOnly group: "ecs", name: "ecs", version: "1.4.2"
	compileOnly group: "edu.ucar", name: "netcdf", version: "4.3.23"
	compileOnly group: "io.netty", name: "netty-all", version: "4.1.48.Final"
	compileOnly group: "javax.ccpp", name: "ccpp", version: "1.0"
	compileOnly group: "javax.portlet", name: "portlet-api", version: "3.0.1"
	compileOnly group: "javax.servlet.jsp.jstl", name: "javax.servlet.jsp.jstl-api", version: "1.2.2"
	compileOnly group: "javax.transaction", name: "javax.transaction-api", version: "1.3"
	compileOnly group: "javax.ws.rs", name: "javax.ws.rs-api", version: "2.1"
	compileOnly group: "javax.xml.soap", name: "saaj-api", version: "1.3"
	compileOnly group: "jaxen", name: "jaxen", version: "1.1.6"
	compileOnly group: "net.fortuna.ical4j", name: "ical4j", version: "1.0-rc3"
	compileOnly group: "net.htmlparser.jericho", name: "jericho-html", version: "3.1"
	compileOnly group: "net.java.dev.jna", name: "jna", version: "4.1.0"
	compileOnly group: "net.sf.jazzy", name: "jazzy", version: "0.5.2-rtext-1.4.1-2"
	compileOnly group: "net.sf.jsr107cache", name: "jsr107cache", version: "1.0"
	compileOnly group: "net.sf.kxml", name: "kxml2", version: "2.3.0"
	compileOnly group: "net.sourceforge.nekohtml", name: "nekohtml", version: "1.9.22"
	compileOnly group: "odmg", name: "odmg", version: "3.0"
	compileOnly group: "org.antlr", name: "antlr", version: "3.0.1"
	compileOnly group: "org.antlr", name: "antlr-runtime", version: "3.0.1"
	compileOnly group: "org.antlr", name: "stringtemplate", version: "3.0"
	compileOnly group: "org.apache.abdera", name: "abdera-bundle", version: "1.1.3"
	compileOnly group: "org.apache.ant", name: "ant", version: "1.10.9"
	compileOnly group: "org.apache.axis", name: "axis-ant", version: "1.4"
	compileOnly group: "org.apache.commons", name: "commons-collections4", version: "4.2"
	compileOnly group: "org.apache.commons", name: "commons-compress", version: "1.19"
	compileOnly group: "org.apache.commons", name: "commons-exec", version: "1.3"
	compileOnly group: "org.apache.commons", name: "commons-lang3", version: "3.9"
	compileOnly group: "org.apache.commons", name: "commons-math", version: "2.0"
	compileOnly group: "org.apache.commons", name: "commons-math3", version: "3.6.1"
	compileOnly group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.5"
	compileOnly group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.9"
	compileOnly group: "org.apache.httpcomponents", name: "httpmime", version: "4.5.5"
	compileOnly group: "org.apache.james", name: "apache-mime4j-core", version: "0.8.3"
	compileOnly group: "org.apache.james", name: "apache-mime4j-dom", version: "0.8.3"
	compileOnly group: "org.apache.logging.log4j", name: "log4j-1.2-api", version: "2.14.1"
	compileOnly group: "org.apache.pdfbox", name: "fontbox", version: "2.0.23"
	compileOnly group: "org.apache.pdfbox", name: "jbig2-imageio", version: "3.0.3"
	compileOnly group: "org.apache.pdfbox", name: "jempbox", version: "1.8.16"
	compileOnly group: "org.apache.pdfbox", name: "pdfbox", version: "2.0.23"
	compileOnly group: "org.apache.poi", name: "poi", version: "4.1.2"
	compileOnly group: "org.apache.poi", name: "poi-ooxml", version: "4.1.2"
	compileOnly group: "org.apache.poi", name: "poi-ooxml-schemas", version: "4.1.2"
	compileOnly group: "org.apache.poi", name: "poi-scratchpad", version: "4.1.2"
	compileOnly group: "org.apache.santuario", name: "xmlsec", version: "1.5.8"
	compileOnly group: "org.apache.tika", name: "tika-core", version: "1.26"
	compileOnly group: "org.apache.tika", name: "tika-parsers", version: "1.26"
	compileOnly group: "org.apache.tomcat", name: "tomcat-jdbc", version: "9.0.43"
	compileOnly group: "org.apache.tomcat", name: "tomcat-juli", version: "9.0.43"
	compileOnly group: "org.apache.ws.commons.axiom", name: "axiom-api", version: "1.2.20"
	compileOnly group: "org.apache.ws.commons.axiom", name: "axiom-impl", version: "1.2.20"
	compileOnly group: "org.apache.xbean", name: "xbean-spring", version: "2.8"
	compileOnly group: "org.apache.xmlbeans", name: "xmlbeans", version: "3.0.2"
	compileOnly group: "org.aspectj", name: "aspectjrt", version: "1.9.5"
	compileOnly group: "org.aspectj", name: "aspectjweaver", version: "1.9.5"
	compileOnly group: "org.ccil.cowan.tagsoup", name: "tagsoup", version: "1.2.1"
	compileOnly group: "org.codehaus.woodstox", name: "wstx-asl", version: "3.2.8"
	compileOnly group: "org.dom4j", name: "dom4j", version: "2.1.3"
	compileOnly group: "org.eclipse.core", name: "runtime", version: "20070801"
	compileOnly group: "org.eclipse.persistence", name: "javax.persistence", version: "2.1.1"
	compileOnly group: "org.freshcookies", name: "freshcookies-security", version: "0.60"
	compileOnly group: "org.gagravarr", name: "vorbis-java-core", version: "0.8"
	compileOnly group: "org.glassfish.jersey.core", name: "jersey-common", version: "2.26"
	compileOnly group: "org.glassfish.web", name: "javax.servlet.jsp.jstl", version: "1.2.3"
	compileOnly group: "org.htmlparser", name: "htmlparser", version: "1.6"
	compileOnly group: "org.im4java", name: "im4java", version: "1.2.0"
	compileOnly group: "org.incava", name: "java-diff", version: "1.1"
	compileOnly group: "org.javassist", name: "javassist", version: "3.27.0-GA"
	compileOnly group: "org.jboss.spec.javax.rmi", name: "jboss-rmi-api_1.0_spec", version: "1.0.5.Final"
	compileOnly group: "org.jdom", name: "jdom", version: "1.1.3"
	compileOnly group: "org.jdom", name: "jdom2", version: "2.0.6"
	compileOnly group: "org.jfree", name: "jcommon", version: "1.0.24"
	compileOnly group: "org.jfree", name: "jfreechart", version: "1.0.19"
	compileOnly group: "org.jodd", name: "jodd-json", version: "6.0.3"
	compileOnly group: "org.jodd", name: "jodd-proxetta", version: "6.0.0"
	compileOnly group: "org.json", name: "json", version: "20180813"
	compileOnly group: "org.jvnet", name: "mimepull", version: "1.3"
	compileOnly group: "org.jvnet.staxex", name: "stax-ex", version: "1.2"
	compileOnly group: "org.mozilla", name: "rhino", version: "1.7R4"
	compileOnly group: "org.openoffice", name: "juh", version: "2.3.1"
	compileOnly group: "org.openoffice", name: "jurt", version: "2.3.1"
	compileOnly group: "org.openoffice", name: "ridl", version: "2.3.1"
	compileOnly group: "org.openoffice", name: "unoil", version: "2.3.1"
	compileOnly group: "org.samba.jcifs", name: "jcifs", version: "1.3.14-kohsuke-1"
	compileOnly group: "org.scribe", name: "scribe", version: "1.0.9"
	compileOnly group: "org.slf4j", name: "jcl-over-slf4j", version: "1.7.2"
	compileOnly group: "org.slf4j", name: "slf4j-api", version: "1.7.26"
	compileOnly group: "org.springframework", name: "spring-aop", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-aspects", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-beans", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-context", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-context-support", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-core", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-expression", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-jdbc", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-jms", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-oxm", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-tx", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-web", version: "5.2.10.RELEASE"
	compileOnly group: "org.springframework", name: "spring-webmvc", version: "5.2.10.RELEASE"
	compileOnly group: "org.tallison", name: "jmatio", version: "1.2"
	compileOnly group: "org.tuckey", name: "urlrewritefilter", version: "4.0.4"
	compileOnly group: "org.tukaani", name: "xz", version: "1.8"
	compileOnly group: "oro", name: "oro", version: "2.0.8"
	compileOnly group: "soap", name: "soap", version: "2.2"
	compileOnly group: "stax", name: "stax-api", version: "1.0.1"
	compileOnly group: "wsdl4j", name: "wsdl4j", version: "1.6.3"
	compileOnly group: "xalan", name: "serializer", version: "2.7.2"
	compileOnly group: "xalan", name: "xalan", version: "2.7.2"
	compileOnly group: "xerces", name: "xercesImpl", version: "2.12.0"
	compileOnly group: "xml-apis", name: "xml-apis", version: "1.4.01"
	compileOnly group: "xpp3", name: "xpp3_min", version: "1.1.4c"
	compileOnly project(":apps:petra:petra-content")
	compileOnly project(":apps:petra:petra-encryptor")
	compileOnly project(":apps:petra:petra-log4j")
	compileOnly project(":apps:petra:petra-mail")
	compileOnly project(":apps:petra:petra-portlet-url-builder")
	compileOnly project(":core:petra:petra-url-pattern-mapper")
	compileOnly project(":apps:petra:petra-xml")
	compileOnly project(":portal:portal-kernel")
	compileOnly project(":portal:util-bridges")
	compileOnly project(":portal:util-java")
	compileOnly project(":portal:util-taglib")
	//compileOnly project(":test:jenkins-results-parser")
	//compileOnly project(":test:poshi:poshi-core")
	compileOnly(group: "net.open-esb.core", name: "jbi_rt", version: "2.4.3") {
		exclude group: "glassfish", module: "appserv-ext"
	}
}

jar {
	doLast {
		copy {
			from jar.archivePath
			into rootProject.file("../${project.name}")
			rename { "${project.name}.jar" }
		}
	}
}

processResources {
	doLast {
		copy {
			from rootProject.file("../definitions")
			into new File(
					sourceSets.main.output.resourcesDir,
					"com/liferay/portal/definitions")
		}

		copy {
			from rootProject.file("../classes")
			include "*.properties"
			into new File(sourceSets.main.output.resourcesDir, "com/liferay/portal/deploy/dependencies")
		}

		copy {
			from rootProject.file("../portal-web/docroot/WEB-INF/tld")
			include "*.tld"
			into new File(sourceSets.main.output.resourcesDir, "com/liferay/portal/deploy/dependencies")
		}

		copy {
			from rootProject.file("../sql")
			include "portal-data-common.sql"
			include "portal-data-counter.sql"
			include "portal-tables.sql"
			include "indexes.properties"
			include "indexes.sql"
			include "sequences.sql"
			include "update-*.sql"
			into new File(sourceSets.main.output.resourcesDir, "com/liferay/portal/tools/sql/dependencie")
		}

		copy {
			from rootProject.file("../classes/log4j2.properties")
			from rootProject.file("../classes/logging.properties")
			into sourceSets.main.output.resourcesDir

		}
	}
}

sourceSets {
	main {
		java {
			srcDirs rootProject.file("../${project.name}/src")
		}
		resources {
			srcDirs rootProject.file("../${project.name}/src")
		}
	}
}

task printSource {
	doLast {
		println "Sources : " + sourceSets.main.allSource.files
		println rootProject.file("../${project.name}/src")
	}
}