<?xml version="1.0"?>

<project name="build-new">
	<import file="build-dependencies.xml" />

	<target name="all" depends="clean">
		<antcall target="deploy" />
	</target>

	<target name="clean">
		<antcall target="depend.all">
			<param name="target" value="clean" />
		</antcall>
	</target>

	<target name="compile">
		<antcall target="depend.all">
			<param name="target" value="compile" />
		</antcall>
	</target>

	<target name="deploy">
		<antcall target="depend.all">
			<param name="target" value="deploy" />
		</antcall>
	</target>

	<target name="install">
		<antcall target="depend.all">
			<param name="target" value="install" />
		</antcall>
	</target>

	<target name="jar">
		<antcall target="depend.all">
			<param name="target" value="jar" />
		</antcall>
	</target>
</project>