dependencies {
	compileOnly project(":portal:portal-impl")
	compileOnly project(":portal:portal-kernel")
	compileOnly project(":portal:portal-test")
	compileOnly group: "junit", name: "junit", version: "4.13.1"
	compileOnly group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	compileOnly group: "org.springframework", name: "spring-test", version: "5.2.2.RELEASE"
	compileOnly project(":core:petra:petra-string")
}

liferay {
	deployDir = file("${liferayHome}/osgi/test")
}