dependencies {
	testIntegrationCompile project(":portal:portal-impl")
	testIntegrationCompile project(":portal:portal-kernel")
	testIntegrationCompile project(":apps:portal-security-sso-ntlm:portal-security-sso-ntlm-api")
	testIntegrationCompile project(":apps:portal:portal-verify-test-util")
	testIntegrationCompile project(":core:petra:petra-string")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}