<?xml version="1.0"?>

<project basedir="." name="portal-impl" xmlns:artifact="antlib:org.apache.maven.artifact.ant">
	<property name="artifactId" value="${ant.project.name}" />
	<property name="groupId" value="com.liferay.portal" />
	<property name="version" value="${lp.version}" />

	<property name="resolve.remote.dependencies" value="true" />

	<extension-point
		name="project-compile-dependencies"
		depends="
			install.portal-service,
			install.portal-test,
			install.util-bridges,
			install.util-java,
			install.util-slf4j"
	/>

	<import file="../build-common.xml" />

	<target name="resolve-remote-dependencies" if="${resolve.remote.dependencies}">
		<artifact:dependencies pathId="project.dependency.classpath" filesetId="project.dependency.fileset">
			<artifact:remoteRepository refid="liferay.maven.remote" />

			<dependency groupId="com.liferay.portal" artifactId="portal-service" version="${lp.version}" />
			<dependency groupId="com.liferay.portal" artifactId="portal-test" version="${lp.version}" />
			<dependency groupId="com.liferay.portal" artifactId="util-bridges" version="${lp.version}" />
			<dependency groupId="com.liferay.portal" artifactId="util-java" version="${lp.version}" />
			<dependency groupId="com.liferay.portal" artifactId="util-slf4j" version="${lp.version}" />
		</artifact:dependencies>
	</target>

	<!-- <pathconvert refid="dependency.fileset" property="dependency.fileset" /> -->

	<!-- <available property="project.dependencies.available">
		<filepath refid="project.dependency.fileset" />
	</available> -->
</project>