<?xml version="1.0"?>

<project basedir="." name="portal-impl" xmlns:artifact="antlib:org.apache.maven.artifact.ant">
	<extension-point
		name="dependencies"
		depends="
			install.portal-service,
			install.portal-service,
			install.portal-test,
			install.util-bridges,
			install.util-java,
			install.util-slf4j"
	/>

	<import file="../build-common.xml" />

	<artifact:dependencies pathId="dependency.classpath">
		<dependency groupId="com.liferay.portal" artifactId="portal-service" version="${lp.version}" />
		<dependency groupId="com.liferay.portal" artifactId="portal-test" version="${lp.version}" />
		<dependency groupId="com.liferay.portal" artifactId="util-bridges" version="${lp.version}" />
		<dependency groupId="com.liferay.portal" artifactId="util-java" version="${lp.version}" />
		<dependency groupId="com.liferay.portal" artifactId="util-slf4j" version="${lp.version}" />
	</artifact:dependencies>
</project>