cleanJar {
	doLast {
		project.delete(rootProject.file("../${project.name}/${project.name}.jar"))
	}
}

classes {
	doLast {
		ant.replace(
			file: "classes/META-INF/liferay-portlet_1_0.tld",
			token: "<short-name>portlet_1_0</short-name>",
			value: "<short-name>portlet</short-name>"
		)

		ant.replace(
			file: "classes/META-INF/liferay-portlet_2_0.tld",
			token: "<short-name>portlet_2_0</short-name>",
			value: "<short-name>portlet</short-name>"
		)
	}
}

dependencies {
	compileOnly group: "com.liferay.alloy-taglibs", name: "alloy-taglib", version: "1.1.14"
	compileOnly group: "javax.portlet", name: "portlet-api", version: "3.0.1"
	compileOnly group: "javax.servlet", name: "javax.servlet-api", version: "3.1.0"
	compileOnly group: "javax.servlet.jsp", name: "jsp-api", version: "2.1"
	compileOnly group: "org.osgi", name: "org.osgi.annotation.versioning", version: "1.1.0"
	compileOnly project(":apps:petra:petra-encryptor")
	compileOnly project(":portal:portal-kernel")
	compileOnly project(":portal:util-java")
}

deploy {
	doLast {
		if (liferay.appServerType == "tomcat") {
			project.copy {
				from project.file("classes/META-INF")
				include "*.tld"
				into new File(liferay.appServerPortalDir, "/WEB-INF/tld")
			}
		}
	}
}

jar {
	doLast {
		copy {
			from jar.archivePath
			into rootProject.file("../${project.name}")
			rename { "${project.name}.jar" }
		}
	}
}


sourceSets {
	main {
		java {
			srcDirs rootProject.file("../${project.name}/src")
		}
		resources {
			srcDirs rootProject.file("../${project.name}/src")
		}
	}
}


//				<copy
//		file="${jar.file}.jar"
//		preservelastmodified="true"
//		todir="${portal-impl.classes.dir}/com/liferay/portal/deploy/dependencies"
//		/>
//
//		<copy
//			preservelastmodified="true"
//			todir="${portal-impl.classes.dir}/com/liferay/portal/deploy/dependencies"
//				>
//				<fileset
//		dir="classes/META-INF"
//		/>
//		</copy>
//
//				<copy
//		file="${jar.file}.jar"
//		preservelastmodified="true"
//		todir="${project.dir}/portal-web/docroot/WEB-INF/lib"
//		/>
//
//		<copy
//			overwrite="true"
//			preservelastmodified="true"
//			todir="${project.dir}/portal-web/docroot/WEB-INF/tld"
//				>
//				<fileset
//		dir="classes/META-INF"
//		includes="*.tld"
//		/>
//		</copy>