<?xml version="1.0"?>

<project basedir="." name="portal-service" xmlns:artifact="antlib:org.apache.maven.artifact.ant">
	<import file="../build-common.xml" />

	<artifact:dependencies pathId="dependency.classpath">
		<dependency groupId="com.liferay" artifactId="aQute.bnd" version="2.3.0" />
		<dependency groupId="javax.servlet" artifactId="javax.servlet-api" version="3.0.1" />
		<dependency groupId="javax.portlet" artifactId="portlet-api" version="2.0" />
		<dependency groupId="javax.mail" artifactId="mail" version="1.4" />

		<remoteRepository id="liferay.maven.remote" url="http://cdn.repository.liferay.com/nexus/content/groups/public" />
	</artifact:dependencies>

	<extension-point name="dependencies" />
</project>