artifact.git.id=82c50934de420de7ccd25ba05e01fb290cf2abf0
artifact.url=https://repository-cdn.liferay.com/nexus/content/repositories/xanadu/com/liferay/plugins/admin-theme/5.0.64/admin-theme-5.0.64.war