<?xml version="1.0" encoding="UTF-8"?>
<ivy-module version="2.0" xmlns:m2="http://ant.apache.org/ivy/maven" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://ant.apache.org/ivy/schemas/ivy.xsd">
	<info organisation="com.liferay.portal" module="util-java">
		<license name="LGPL 2.1" url="http://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt" />

		<description homepage="http://www.liferay.com" />
	</info>

	<configurations>
		<conf name="core" />
		<conf name="default" />
	</configurations>

	<publications>
		<artifact conf="core" name="util-java" />
	</publications>

	<dependencies defaultconf="default">
		<dependency name="ant-apache-bsf" org="org.apache.ant" rev="1.8.3" />
		<dependency name="aQute.bnd" org="com.liferay" rev="2.3.0.20140225-161137" />
		<dependency name="aspectjweaver" org="org.aspectj" rev="1.8.0" />
		<dependency name="axis" org="org.apache.axis" rev="1.4" />
		<dependency name="axis-ant" org="org.apache.axis" rev="1.4" />
		<dependency name="com.liferay.ibm.icu.icu4j" org="com.liferay" rev="4.0.1" />
		<dependency name="commons-beanutils" org="commons-beanutils" rev="1.8.2" />
		<dependency name="commons-validator" org="commons-validator" rev="1.3.1" />
		<dependency name="freemarker" org="org.freemarker" rev="2.3.17" />
		<dependency name="hibernate-core" org="org.hibernate" rev="3.6.10.Final" />
		<dependency name="ical4j" org="org.mnode.ical4j" rev="1.0.2" />
		<dependency name="javax.servlet-api" org="javax.servlet" rev="3.0.1" />
		<dependency name="jaxrpc" org="javax.xml" rev="1.1" />
		<dependency name="jazzy-core" org="net.sf.jazzy" rev="0.5.2" />
		<dependency name="log4j" org="log4j" rev="1.2.16" />
		<dependency name="mail" org="javax.mail" rev="1.4" />
		<dependency name="poi" org="org.apache.poi" rev="3.11" />
		<dependency name="portal-service" org="com.liferay.portal" rev="${ivy.core.dependency.revision}" />
		<dependency name="portlet-api" org="javax.portlet" rev="2.0" />
		<dependency name="rome" org="rome" rev="1.0" />
		<dependency name="spring-tx" org="org.springframework" rev="3.2.10.RELEASE" />
	</dependencies>
</ivy-module>
