dependencies {
	testIntegrationCompile project(":portal:portal-impl")
	testIntegrationCompile project(":portal:util-java")
	testIntegrationCompile project(":apps:petra:petra-xml")
	testIntegrationCompile project(":core:petra:petra-sql-dsl-api")
	testIntegrationCompile project(":dxp:apps:saml:saml-persistence-api")
	testIntegrationCompile project(":dxp:apps:saml:saml-persistence-service")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}