dependencies {
	compileOnly group: "com.liferay", name: "com.dumbster.smtp", version: "02856255a6cc7f"
	compileOnly group: "com.liferay.portletmvc4spring", name: "com.liferay.portletmvc4spring.test", version: "5.2.1"
	compileOnly group: "javax.portlet", name: "portlet-api", version: "3.0.1"
	compileOnly group: "junit", name: "junit", version: "4.13.1"
	compileOnly group: "com.liferay", name: "org.apache.logging.log4j", version: "2.14.1.LIFERAY-PATCHED-1"
	compileOnly group: "com.liferay", name: "org.apache.logging.log4j.core", version: "2.14.1.LIFERAY-PATCHED-1"
	compileOnly group: "org.apache.logging.log4j", name: "log4j-1.2-api", version: "2.14.1"
	compileOnly group: "org.apache.felix", name: "org.apache.felix.http.servlet-api", version: "1.1.2"
	compileOnly group: "org.aspectj", name: "aspectjrt", version: "1.9.5"
	compileOnly group: "org.aspectj", name: "aspectjweaver", version: "1.9.5"
	compileOnly group: "org.springframework", name: "spring-test", version: "5.2.3.RELEASE"
	compileOnly project(":portal:portal-impl")
	compileOnly project(":portal:portal-kernel")
	compileOnly project(":apps:petra:petra-log4j")
}

sourceSets {
	main {
		java {
			srcDirs rootProject.file("../${project.name}/src")
		}
		resources {
			srcDirs rootProject.file("../${project.name}/src")
		}
	}
}