dependencies {
	compileOnly project(":portal:portal-kernel")
	compileOnly project(":portal:portal-test")
	compileOnly group: "junit", name: "junit", version: "4.13.1"
	compileOnly project(":apps:change-tracking:change-tracking-api")
	compileOnly project(":core:petra:petra-lang")
}

liferay {
	deployDir = file("${liferayHome}/osgi/test")
}