dependencies {
	testIntegrationCompile project(":portal:portal-impl")
	testIntegrationCompile project(":portal:portal-kernel")
	testIntegrationCompile project(":apps:petra:petra-encryptor")
	testIntegrationCompile project(":core:petra:petra-function")
	testIntegrationCompile project(":core:petra:petra-reflect")
	testIntegrationCompile project(":core:petra:petra-string")
	testIntegrationCompile project(":test:arquillian-extension-junit-bridge")
}