apply from: file('../build-common.gradle')
apply plugin: 'war'

task deployTomcat(type: Copy, dependsOn: war)

cleanWar {
	doLast {
		project.delete(rootProject.file("../${project.name}/${project.name}.war"))
	}
}

jar {
	enabled false
}

deploy {
	dependsOn deployTomcat
}

deployTomcat {
	from zipTree(war.archivePath)
	into liferay.appServerPortalDir
}

dependencies {
	compile project(":portal:portal-impl")
}

webAppDirName = rootProject.file("../${project.name}/docroot")

war {
	doLast {
		copy {
			from war.archivePath
			into rootProject.file("../${project.name}")
			rename { "${project.name}.war" }
		}
	}
}